[project]
name = "assets"
version = "0.1.0"
description = "GitHub asset management with lock files and extensive configuration"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
 "colorama>=0.4.6",
 "platformdirs>=4.3.8",
 "requests>=2.32.3",
 "semver>=3.0.4",
 "toml>=0.10.2",
]
